// ======================================================
// JOBFAST CATEGORIES & PROFESSIONS
// ======================================================

export const CATEGORIES = {
  BUSINESS_DIRECTORY: {
    id: 'business_directory',
    label: 'Sipèvizè Biznis',
    description: 'Konpayi, Estabilisyon ak Entèpriz',
    icon: '🏢',
    color: 'bg-blue-500',
    professions: [
      'company',
      'restaurant',
      'hospital',
      'clinic',
      'hotel',
      'office',
      'lawyer',
      'mechanic',
      'tour_guide',
      'organization',
    ],
  },
  MARKETPLACE: {
    id: 'marketplace',
    label: 'Mache Yelektwòn',
    description: 'Vann ak Achte Pwodwi',
    icon: '🛒',
    color: 'bg-green-500',
    professions: ['seller', 'property', 'vehicle', 'goods', 'services'],
  },
  SERVICES_ON_DEMAND: {
    id: 'services_on_demand',
    label: 'Sèvis sou Demann',
    description: 'Mande Pwofesyonèl pou Sèvis',
    icon: '🔧',
    color: 'bg-orange-500',
    professions: [
      'chef',
      'plumber',
      'doctor',
      'nurse',
      'taxi',
      'delivery',
      'cleaning',
      'videographer',
      'designer',
      'construction',
    ],
  },
  TOURISM: {
    id: 'tourism',
    label: 'Turizm',
    description: 'Vwayaj ak Lodman',
    icon: '✈️',
    color: 'bg-purple-500',
    professions: ['hotel', 'resort', 'guide', 'restaurant', 'transport', 'activity'],
  },
  CREATOR_ECONOMY: {
    id: 'creator_economy',
    label: 'Atís ak Kreyatè',
    description: 'Mizik, Atizana ak Desen',
    icon: '🎨',
    color: 'bg-pink-500',
    professions: [
      'musician',
      'artist',
      'designer',
      'content_creator',
      'photographer',
      'writer',
    ],
  },
  IMPACT_NGO: {
    id: 'impact_ngo',
    label: 'Òganizasyon Sosyal',
    description: 'Sante, Edikasyon ak Sipò',
    icon: '❤️',
    color: 'bg-red-500',
    professions: [
      'ngo',
      'charity',
      'health_organization',
      'education',
      'social_support',
    ],
  },
};

export const PROFESSION_METADATA = {
  // BUSINESS DIRECTORY
  company: {
    category: 'business_directory',
    label: 'Konpayi',
    icon: '🏢',
    requiredFields: ['businessName', 'industry', 'businessType', 'location'],
    optionalFields: [
      'employees',
      'yearEstablished',
      'website',
      'description',
      'contactPerson',
    ],
    fieldTypes: {
      businessName: 'text',
      industry: 'select',
      businessType: 'select',
      employees: 'number',
      yearEstablished: 'number',
      website: 'url',
      description: 'textarea',
      contactPerson: 'text',
      location: 'location',
    },
  },
  restaurant: {
    category: 'business_directory',
    label: 'Restoran',
    icon: '🍽️',
    requiredFields: ['restaurantName', 'cuisine', 'location'],
    optionalFields: ['seatingCapacity', 'hours', 'specialties', 'phone', 'website'],
    fieldTypes: {
      restaurantName: 'text',
      cuisine: 'select',
      seatingCapacity: 'number',
      hours: 'text',
      specialties: 'textarea',
      location: 'location',
    },
  },
  hospital: {
    category: 'business_directory',
    label: 'Lopital',
    icon: '🏥',
    requiredFields: ['hospitalName', 'services', 'location'],
    optionalFields: ['beds', 'doctors', 'emergencyService', 'phone', 'website'],
    fieldTypes: {
      hospitalName: 'text',
      services: 'textarea',
      beds: 'number',
      emergencyService: 'checkbox',
      location: 'location',
    },
  },
  clinic: {
    category: 'business_directory',
    label: 'Klinik',
    icon: '⚕️',
    requiredFields: ['clinicName', 'specialization', 'location'],
    optionalFields: ['doctors', 'hours', 'phone', 'website'],
    fieldTypes: {
      clinicName: 'text',
      specialization: 'select',
      doctors: 'number',
      location: 'location',
    },
  },
  hotel: {
    category: 'business_directory',
    label: 'Hotel',
    icon: '🏨',
    requiredFields: ['hotelName', 'rooms', 'location'],
    optionalFields: ['stars', 'amenities', 'price', 'phone', 'website'],
    fieldTypes: {
      hotelName: 'text',
      rooms: 'number',
      stars: 'select',
      amenities: 'textarea',
      location: 'location',
    },
  },
  office: {
    category: 'business_directory',
    label: 'Biwo',
    icon: '🏛️',
    requiredFields: ['officeName', 'industry', 'location'],
    optionalFields: ['employees', 'squareFeet', 'phone', 'website'],
    fieldTypes: {
      officeName: 'text',
      industry: 'select',
      employees: 'number',
      location: 'location',
    },
  },
  lawyer: {
    category: 'business_directory',
    label: 'Avoka',
    icon: '⚖️',
    requiredFields: ['fullName', 'specialization', 'barNumber', 'location'],
    optionalFields: ['yearsExperience', 'phone', 'website', 'bio'],
    fieldTypes: {
      fullName: 'text',
      specialization: 'select',
      barNumber: 'text',
      yearsExperience: 'number',
      location: 'location',
      bio: 'textarea',
    },
  },
  mechanic: {
    category: 'business_directory',
    label: 'Mekanisyen',
    icon: '🔧',
    requiredFields: ['shopName', 'vehicleTypes', 'location'],
    optionalFields: ['specialization', 'yearsExperience', 'phone', 'website'],
    fieldTypes: {
      shopName: 'text',
      vehicleTypes: 'select',
      specialization: 'textarea',
      yearsExperience: 'number',
      location: 'location',
    },
  },
  tour_guide: {
    category: 'business_directory',
    label: 'Gid Turizm',
    icon: '🗺️',
    requiredFields: ['fullName', 'languages', 'location'],
    optionalFields: ['yearsExperience', 'specialties', 'phone', 'certifications'],
    fieldTypes: {
      fullName: 'text',
      languages: 'select',
      yearsExperience: 'number',
      specialties: 'textarea',
      location: 'location',
      certifications: 'textarea',
    },
  },
  organization: {
    category: 'business_directory',
    label: 'Òganizasyon',
    icon: '🤝',
    requiredFields: ['organizationName', 'mission', 'location'],
    optionalFields: ['foundedYear', 'members', 'website', 'phone'],
    fieldTypes: {
      organizationName: 'text',
      mission: 'textarea',
      foundedYear: 'number',
      members: 'number',
      location: 'location',
    },
  },

  // MARKETPLACE
  seller: {
    category: 'marketplace',
    label: 'Vendè',
    icon: '👤',
    requiredFields: ['storeName', 'productCategories', 'location'],
    optionalFields: ['yearsInBusiness', 'website', 'phone', 'bio'],
    fieldTypes: {
      storeName: 'text',
      productCategories: 'select',
      yearsInBusiness: 'number',
      location: 'location',
    },
  },
  property: {
    category: 'marketplace',
    label: 'Propiete',
    icon: '🏠',
    requiredFields: ['propertyType', 'location', 'price'],
    optionalFields: ['squareFeet', 'bedrooms', 'bathrooms', 'description'],
    fieldTypes: {
      propertyType: 'select',
      location: 'location',
      price: 'number',
      squareFeet: 'number',
      bedrooms: 'number',
      bathrooms: 'number',
      description: 'textarea',
    },
  },
  vehicle: {
    category: 'marketplace',
    label: 'Machin',
    icon: '🚗',
    requiredFields: ['make', 'model', 'year', 'price'],
    optionalFields: ['mileage', 'condition', 'color', 'transmission'],
    fieldTypes: {
      make: 'select',
      model: 'text',
      year: 'number',
      price: 'number',
      mileage: 'number',
      condition: 'select',
      color: 'select',
      transmission: 'select',
    },
  },
  goods: {
    category: 'marketplace',
    label: 'Pwodwi',
    icon: '📦',
    requiredFields: ['productName', 'category', 'price'],
    optionalFields: ['quantity', 'condition', 'description'],
    fieldTypes: {
      productName: 'text',
      category: 'select',
      price: 'number',
      quantity: 'number',
      condition: 'select',
      description: 'textarea',
    },
  },
  services: {
    category: 'marketplace',
    label: 'Sèvis',
    icon: '🛠️',
    requiredFields: ['serviceName', 'category', 'priceRange'],
    optionalFields: ['description', 'availability', 'serviceArea'],
    fieldTypes: {
      serviceName: 'text',
      category: 'select',
      priceRange: 'select',
      description: 'textarea',
      availability: 'select',
      serviceArea: 'text',
    },
  },

  // SERVICES ON DEMAND
  chef: {
    category: 'services_on_demand',
    label: 'Chef Lakay',
    icon: '👨‍🍳',
    requiredFields: ['fullName', 'cuisineTypes', 'location'],
    optionalFields: ['yearsExperience', 'specialties', 'certifications', 'phone'],
    fieldTypes: {
      fullName: 'text',
      cuisineTypes: 'select',
      yearsExperience: 'number',
      specialties: 'textarea',
      location: 'location',
    },
  },
  plumber: {
    category: 'services_on_demand',
    label: 'Plonbye',
    icon: '🔧',
    requiredFields: ['fullName', 'serviceTypes', 'location'],
    optionalFields: ['yearsExperience', 'certifications', 'hourlyRate', 'phone'],
    fieldTypes: {
      fullName: 'text',
      serviceTypes: 'select',
      yearsExperience: 'number',
      hourlyRate: 'number',
      location: 'location',
    },
  },
  doctor: {
    category: 'services_on_demand',
    label: 'Doktè',
    icon: '👨‍⚕️',
    requiredFields: ['fullName', 'specialization', 'licenseNumber', 'location'],
    optionalFields: ['yearsExperience', 'languages', 'phone', 'consultationFee'],
    fieldTypes: {
      fullName: 'text',
      specialization: 'select',
      licenseNumber: 'text',
      yearsExperience: 'number',
      languages: 'select',
      consultationFee: 'number',
      location: 'location',
    },
  },
  nurse: {
    category: 'services_on_demand',
    label: 'Enfèmyè',
    icon: '👩‍⚕️',
    requiredFields: ['fullName', 'certification', 'location'],
    optionalFields: ['yearsExperience', 'specialization', 'hourlyRate', 'phone'],
    fieldTypes: {
      fullName: 'text',
      certification: 'text',
      yearsExperience: 'number',
      specialization: 'select',
      hourlyRate: 'number',
      location: 'location',
    },
  },
  taxi: {
    category: 'services_on_demand',
    label: 'Taksi',
    icon: '🚕',
    requiredFields: ['fullName', 'vehicleType', 'licenseNumber', 'location'],
    optionalFields: ['yearsExperience', 'languages', 'phone'],
    fieldTypes: {
      fullName: 'text',
      vehicleType: 'select',
      licenseNumber: 'text',
      yearsExperience: 'number',
      languages: 'select',
      location: 'location',
    },
  },
  delivery: {
    category: 'services_on_demand',
    label: 'Delivre',
    icon: '📦',
    requiredFields: ['fullName', 'serviceArea', 'location'],
    optionalFields: ['vehicleType', 'yearsExperience', 'phone', 'ratePerKm'],
    fieldTypes: {
      fullName: 'text',
      serviceArea: 'text',
      vehicleType: 'select',
      yearsExperience: 'number',
      ratePerKm: 'number',
      location: 'location',
    },
  },
  cleaning: {
    category: 'services_on_demand',
    label: 'Netwayaj',
    icon: '🧹',
    requiredFields: ['fullName', 'serviceTypes', 'location'],
    optionalFields: ['yearsExperience', 'teamSize', 'hourlyRate', 'phone'],
    fieldTypes: {
      fullName: 'text',
      serviceTypes: 'select',
      yearsExperience: 'number',
      teamSize: 'number',
      hourlyRate: 'number',
      location: 'location',
    },
  },
  videographer: {
    category: 'services_on_demand',
    label: 'Videograf',
    icon: '🎥',
    requiredFields: ['fullName', 'serviceTypes', 'location'],
    optionalFields: ['yearsExperience', 'portfolio', 'hourlyRate', 'phone'],
    fieldTypes: {
      fullName: 'text',
      serviceTypes: 'select',
      yearsExperience: 'number',
      portfolio: 'url',
      hourlyRate: 'number',
      location: 'location',
    },
  },
  designer: {
    category: 'services_on_demand',
    label: 'Desen',
    icon: '🎨',
    requiredFields: ['fullName', 'designType', 'location'],
    optionalFields: ['yearsExperience', 'portfolio', 'hourlyRate', 'phone'],
    fieldTypes: {
      fullName: 'text',
      designType: 'select',
      yearsExperience: 'number',
      portfolio: 'url',
      hourlyRate: 'number',
      location: 'location',
    },
  },
  construction: {
    category: 'services_on_demand',
    label: 'Konstriksyon',
    icon: '👷',
    requiredFields: ['fullName', 'role', 'location'],
    optionalFields: ['yearsExperience', 'specialties', 'hourlyRate', 'phone'],
    fieldTypes: {
      fullName: 'text',
      role: 'select',
      yearsExperience: 'number',
      specialties: 'textarea',
      hourlyRate: 'number',
      location: 'location',
    },
  },

  // TOURISM
  tourism_hotel: {
    category: 'tourism',
    label: 'Hotel',
    icon: '🏨',
    requiredFields: ['hotelName', 'rooms', 'location'],
    optionalFields: ['stars', 'amenities', 'pricePerNight', 'phone', 'website'],
    fieldTypes: {
      hotelName: 'text',
      rooms: 'number',
      stars: 'select',
      amenities: 'textarea',
      pricePerNight: 'number',
      location: 'location',
    },
  },
  resort: {
    category: 'tourism',
    label: 'Rezò',
    icon: '🏖️',
    requiredFields: ['resortName', 'location', 'amenities'],
    optionalFields: ['rooms', 'pricePerNight', 'website', 'phone'],
    fieldTypes: {
      resortName: 'text',
      location: 'location',
      amenities: 'textarea',
      rooms: 'number',
      pricePerNight: 'number',
    },
  },
  guide: {
    category: 'tourism',
    label: 'Gid',
    icon: '🗺️',
    requiredFields: ['fullName', 'languages', 'location'],
    optionalFields: ['specialties', 'yearsExperience', 'phone', 'hourlyRate'],
    fieldTypes: {
      fullName: 'text',
      languages: 'select',
      specialties: 'textarea',
      yearsExperience: 'number',
      hourlyRate: 'number',
      location: 'location',
    },
  },
  tourism_restaurant: {
    category: 'tourism',
    label: 'Restoran',
    icon: '🍽️',
    requiredFields: ['restaurantName', 'cuisine', 'location'],
    optionalFields: ['website', 'phone', 'seatingCapacity', 'averagePrice'],
    fieldTypes: {
      restaurantName: 'text',
      cuisine: 'select',
      location: 'location',
      seatingCapacity: 'number',
      averagePrice: 'number',
    },
  },
  transport: {
    category: 'tourism',
    label: 'Tranpòtasyon',
    icon: '🚌',
    requiredFields: ['companyName', 'vehicleType', 'location'],
    optionalFields: ['capacity', 'phone', 'website'],
    fieldTypes: {
      companyName: 'text',
      vehicleType: 'select',
      capacity: 'number',
      location: 'location',
    },
  },
  activity: {
    category: 'tourism',
    label: 'Aktivite',
    icon: '🎪',
    requiredFields: ['activityName', 'type', 'location'],
    optionalFields: ['pricePerPerson', 'maxParticipants', 'description', 'phone'],
    fieldTypes: {
      activityName: 'text',
      type: 'select',
      pricePerPerson: 'number',
      maxParticipants: 'number',
      description: 'textarea',
      location: 'location',
    },
  },

  // CREATOR ECONOMY
  musician: {
    category: 'creator_economy',
    label: 'Mizisyen',
    icon: '🎵',
    requiredFields: ['fullName', 'genres', 'location'],
    optionalFields: ['yearsExperience', 'spotifyUrl', 'bookingFee', 'phone'],
    fieldTypes: {
      fullName: 'text',
      genres: 'select',
      yearsExperience: 'number',
      spotifyUrl: 'url',
      bookingFee: 'number',
      location: 'location',
    },
  },
  artist: {
    category: 'creator_economy',
    label: 'Atís',
    icon: '🖌️',
    requiredFields: ['fullName', 'artType', 'location'],
    optionalFields: ['yearsExperience', 'portfolio', 'pricePerPiece', 'phone'],
    fieldTypes: {
      fullName: 'text',
      artType: 'select',
      yearsExperience: 'number',
      portfolio: 'url',
      pricePerPiece: 'number',
      location: 'location',
    },
  },
  creator_designer: {
    category: 'creator_economy',
    label: 'Desen',
    icon: '🎨',
    requiredFields: ['fullName', 'designSpecialty', 'location'],
    optionalFields: ['yearsExperience', 'portfolio', 'hourlyRate', 'phone'],
    fieldTypes: {
      fullName: 'text',
      designSpecialty: 'select',
      yearsExperience: 'number',
      portfolio: 'url',
      hourlyRate: 'number',
      location: 'location',
    },
  },
  content_creator: {
    category: 'creator_economy',
    label: 'Kreyatè Kontan',
    icon: '📱',
    requiredFields: ['fullName', 'platform', 'location'],
    optionalFields: ['followers', 'niche', 'sponsorshipFee', 'socialLinks'],
    fieldTypes: {
      fullName: 'text',
      platform: 'select',
      followers: 'number',
      niche: 'select',
      sponsorshipFee: 'number',
      location: 'location',
    },
  },
  photographer: {
    category: 'creator_economy',
    label: 'Fotograf',
    icon: '📸',
    requiredFields: ['fullName', 'specialization', 'location'],
    optionalFields: ['yearsExperience', 'portfolio', 'pricePerShoot', 'phone'],
    fieldTypes: {
      fullName: 'text',
      specialization: 'select',
      yearsExperience: 'number',
      portfolio: 'url',
      pricePerShoot: 'number',
      location: 'location',
    },
  },
  writer: {
    category: 'creator_economy',
    label: 'Ekriven',
    icon: '✍️',
    requiredFields: ['fullName', 'genre', 'location'],
    optionalFields: ['yearsExperience', 'website', 'pricePerWord', 'phone'],
    fieldTypes: {
      fullName: 'text',
      genre: 'select',
      yearsExperience: 'number',
      website: 'url',
      pricePerWord: 'number',
      location: 'location',
    },
  },

  // IMPACT/NGO
  ngo: {
    category: 'impact_ngo',
    label: 'ONG',
    icon: '🤝',
    requiredFields: ['organizationName', 'mission', 'location'],
    optionalFields: ['foundedYear', 'members', 'website', 'phone'],
    fieldTypes: {
      organizationName: 'text',
      mission: 'textarea',
      foundedYear: 'number',
      members: 'number',
      location: 'location',
    },
  },
  charity: {
    category: 'impact_ngo',
    label: 'Charite',
    icon: '❤️',
    requiredFields: ['organizationName', 'cause', 'location'],
    optionalFields: ['website', 'phone', 'registrationNumber'],
    fieldTypes: {
      organizationName: 'text',
      cause: 'textarea',
      registrationNumber: 'text',
      location: 'location',
    },
  },
  health_organization: {
    category: 'impact_ngo',
    label: 'Òganizasyon Sante',
    icon: '🏥',
    requiredFields: ['organizationName', 'services', 'location'],
    optionalFields: ['foundedYear', 'staff', 'website', 'phone'],
    fieldTypes: {
      organizationName: 'text',
      services: 'textarea',
      foundedYear: 'number',
      staff: 'number',
      location: 'location',
    },
  },
  education: {
    category: 'impact_ngo',
    label: 'Edikasyon',
    icon: '🎓',
    requiredFields: ['organizationName', 'programs', 'location'],
    optionalFields: ['students', 'teachers', 'website', 'phone'],
    fieldTypes: {
      organizationName: 'text',
      programs: 'textarea',
      students: 'number',
      teachers: 'number',
      location: 'location',
    },
  },
  social_support: {
    category: 'impact_ngo',
    label: 'Sipò Sosyal',
    icon: '🤲',
    requiredFields: ['organizationName', 'supportType', 'location'],
    optionalFields: ['beneficiaries', 'foundedYear', 'website', 'phone'],
    fieldTypes: {
      organizationName: 'text',
      supportType: 'textarea',
      beneficiaries: 'number',
      foundedYear: 'number',
      location: 'location',
    },
  },
};

export const getCategoryById = (categoryId) => {
  return Object.values(CATEGORIES).find((cat) => cat.id === categoryId);
};

export const getProfessionsByCategory = (categoryId) => {
  const category = getCategoryById(categoryId);
  return category?.professions || [];
};

export const getProfessionMetadata = (professionId) => {
  return PROFESSION_METADATA[professionId] || null;
};

export const getRequiredFields = (professionId) => {
  return PROFESSION_METADATA[professionId]?.requiredFields || [];
};

export const getOptionalFields = (professionId) => {
  return PROFESSION_METADATA[professionId]?.optionalFields || [];
};
